### PR TITLE
Advanced Search Default Configuration Files

### PR DESCRIPTION
**Pull request by alliomeria**
For https://github.com/esmero/archipelago-deployment/issues/259

@DiegoPino, please let me know if these look ok, need any adjustments. Thank you very much!

### CODE REVIEW

**Comment by alliomeria** [comment]
Just a moment, I need the custom block content too... [update: all ok now, thank you!]

**Comment by DiegoPino** [comment]
@alliomeria this so good! Thanks so much. Will give it later today a spin and then merge. Awesome!

**Comment by alliomeria** [comment]
Ok @DiegoPino, moved the files to the different folders as needed and also added the menu content items. How does everything look?

**Comment by DiegoPino** [comment]
@alliomeria merging this. Thanks so much. I will issue a full update of archipelago deployment 1.3.0 to Drupal 10.1 in a little while so this can be used and will also update the "upgrade to drupal 10" instructions bc people will need them to be 10.1 aware. Thanks again

**Review by DiegoPino — APPROVED** [review]
All checked and works well. Thanks for your contribution @alliomeria!

**Pull request merged**
