### PR TITLE
ISSUE-54: Updated display_field_copy module so is Drupal 9 compatible

### PR DESCRIPTION
**Pull request by pcambra**
Related to #54

### CODE REVIEW

**Comment by DiegoPino** [comment]
@pcambra should we better go RC2 here? Let me clone RC1 and I change the base

**Comment by DiegoPino** [comment]
Perfect. Merging

**Comment by DiegoPino** [comment]
We need another for 1.0.0-RC2D9

**Comment by giancarlobi** [comment]
@DiegoPino @pcambra I found some time (very little) and updated my archipelago with sudo -u www-data composer require "drupal/display_field_copy:^2.0" and all seems ok. Just to sign I'm alive, friends

**Pull request merged**
