### PR TITLE
ISSUE-8: Create simple Archipelago Packages Update Script

### PR DESCRIPTION
**Pull request by DiegoPino**
# What is new?

See #8 
For people running/testing archipelago during a release or in between, having a simple script to update all archipelago dependant packages at once seems like a good idea, so here there is a too basic bash script that does it

# How to test?

You have archipelago running and are super happy or confused. We just updated webform_strawberryfield to fix a bug. How do you apply that to your shiny new thing?

Run

`docker exec -ti esmero-php bash -c 'scripts/archipelago/update.sh'`
You should see this if all is already up to date
```SHELL
Updating Archipelago Packages to whatever is latest in this release!
Running as root
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)                
Nothing to install or update
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
 [success] Cache rebuild complete.
Taking ownership of drupal modules for the www-data user    
If you see no errors, you are up to date!
```
And if not something like
strawberryfield/format_strawberryfield (dev-8.x-1.0-beta1 d130e5c): Updating d130e5c4b7 from cache 

# Note
This will try to run `drush cr`; only if Drupal is actually installed. Edge case if people don't follow instructions and try run `update.sh` before installing Archipelago which funny enough will install every package, so Don't do it.)

@giancarlobi this is the missing piece to test the latest https://github.com/esmero/webform_strawberryfield/commit/5e20cc41f7ee6ee37a4b6269f2fc84768ec7fc54. Hope it works for you.

### CODE REVIEW

**Comment by DiegoPino** [comment]
@giancarlobi if you have some time, could you give this a soft review and if you feel its ok merge? I would like to ad this to the documentation so people have this around for the upcoming beta2. Thanks a lot!

**Comment by giancarlobi** [comment]
I created the script file: ~/archipelago-deployment/scripts/archipelago/update.sh as https://github.com/esmero/archipelago-deployment/pull/9/files#diff-08e52a78ebdd46e6e9bc83436f44ea02
Then `cd ~/archipelago-deployment` and launched `docker exec -ti -u www-data esmero-php bash -c 'scripts/archipelago/update.sh'` with permission error. Maybe we have to remove `-u www-data` as www-data has no permission on .git while my current user has ?
Error log:
`Updating Archipelago Packages to whatever is latest in this release!`
```
Running as
www-data
Loading composer repositories with package information                                                   Updating dependencies (including require-dev)                             Package operations: 0 installs, 1 update, 0 removals
  - Updating strawberryfield/webform_strawberryfield dev-8.x-1.0-beta1 (1fd7b50 => 5e20cc4):  Checking out 5e20cc41f7
    Update failed (Failed to clone https://github.com/esmero/webform_strawberryfield.git via https, ssh protocols, aborting.

- https://github.com/esmero/webform_strawberryfield.git
  error: could not lock config file .git/config: Permission denied
  fatal: could not set 'remote.composer.url' to 'https://github.com/esmero/webform_strawberryfield.git'
  error: cannot open .git/FETCH_HEAD: Permission denied

- git@github.com:esmero/webform_strawberryfield.git
  error: could not lock config file .git/config: Permission denied
  fatal: could not set 'remote.composer.url' to 'git@github.com:esmero/webform_strawberryfield.git'
  error: cannot open .git/FETCH_HEAD: Permission denied
)
    Would you like to try reinstalling the package instead [yes]? no


  [RuntimeException]
  Failed to clone https://github.com/esmero/webform_strawberryfield.git via https, ssh protocols, aborting.

  - https://github.com/esmero/webform_strawberryfield.git
    error: could not lock config file .git/config: Permission denied
    fatal: could not set 'remote.composer.url' to 'https://github.com/esmero/webform_strawberryfield.git'
    error: cannot open .git/FETCH_HEAD: Permission denied

  - git@github.com:esmero/webform_strawberryfield.git
    error: could not lock config file .git/config: Permission denied
    fatal: could not set 'remote.composer.url' to 'git@github.com:esmero/webform_strawberryfield.git'
    error: cannot open .git/FETCH_HEAD: Permission denied


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

Updating strawberryfield packages via composer failed`
```

**Comment by DiegoPino** [comment]
@giancarlobi this seems to be related to the fact that all .git don't belong to the www-data user? Was this a fresh install?  We recently added to the docs an extra command (in the drush script invocation that launches the drupal install) where we chown -R www-data everything. Here https://github.com/esmero/archipelago-deployment/blame/8.x-1.0-beta1/docs/ubuntu.md#L128
And same goes for OSX: But, that said i have no issue with running this as root, i was just trying to avoid that alert composer gives us about running as root that scares some people! Not me jajaja.
We can also do the following maybe.
Run as root and then again chown www-data? in the same script? What would you suggest? Thanks a lot for your review!

**Comment by giancarlobi** [comment]
It's my Archipelago+Docker fresh install as doc (see below).
The issue is that .git directory into archipelago-deployment folder has my user permission as it is outside of docker site folder.
In addition, along installation when we run a script never we use -u option (i.e. `docker exec -ti esmero-php bash -c 'scripts/archipelago/setup.sh'`).
I suggest to run `docker exec -ti esmero-php bash -c 'scripts/archipelago/update.sh'` without -u option as during installation steps.
@DiegoPino I wait for your reply before go on.

```
git clone https://github.com/esmero/archipelago-deployment.git archipelago-deployment
cd archipelago-deployment
git checkout 8.x-1.0-beta1
cp docker-compose-nginx.yml docker-compose.yml
docker-compose up -d

sudo chown -R 100:100 persistent/iiifcache
sudo chown -R 8983:8983 persistent/solrcore
docker exec -ti esmero-php bash -c "chown -R www-data:www-data private"

$ docker ps
CONTAINER ID        IMAGE                              COMMAND                  CREATED              STATUS                        PORTS                    NAMES
338186a6c5d8        nginx                              "nginx -g 'daemon of…"   About a minute ago   Up About a minute             0.0.0.0:8001->80/tcp     esmero-web
eeb987cfa64d        solr:7.5.0                         "docker-entrypoint.s…"   About a minute ago   Up 13 seconds                 0.0.0.0:8983->8983/tcp   esmero-solr
74b640bed50e        esmero/php-7.3-fpm:8.x-1.0-beta1   "docker-php-entrypoi…"   About a minute ago   Up About a minute             9000/tcp                 esmero-php
013de8fa1c7d        esmero/cantaloupe-s3:4.0.3         "sh -c 'java -Dcanta…"   About a minute ago   Up About a minute             0.0.0.0:8183->8182/tcp   esmero-cantaloupe
f7a0744b5962        minio/minio:latest                 "/usr/bin/docker-ent…"   About a minute ago   Up About a minute (healthy)   0.0.0.0:9000->9000/tcp   esmero-minio
1b5e3f39c5f4        mysql:5.7                          "docker-entrypoint.s…"   About a minute ago   Up About a minute             3306/tcp, 33060/tcp      esmero-db

http://150.145.48.59:9000/minio/
create archipelago bucket : OK

docker exec -ti esmero-php bash -c "composer install"
docker exec -ti esmero-php bash -c 'scripts/archipelago/setup.sh'
docker exec -ti esmero-php bash -c "cd web;../vendor/bin/drush -y si --verbose config_installer  config_installer_sync_configure_form.sync_directory=/var/www/html/config/sync/ --db-url=mysql://root:esmerodb@esmero-db/drupal8 --account-name=admin --account-pass=archipelago -r=/var/www/html/web --sites-subdir=default --notify=false install_configure_form.enable_update_status_module=NULL install_configure_form.enable_update_status_emails=NULL;drush cr;chown -R www-data:www-data sites;"
[success] Installation complete.
 [success] Cache rebuild complete.

docker exec -ti esmero-php bash -c 'drush ucrt demo --password="demo"; drush urol metadata_pro "demo"'
docker exec -ti esmero-php bash -c 'drush ucrt jsonapi --password="jsonapi"; drush urol metadata_pro "jsonapi"'

docker exec -ti esmero-php bash -c 'scripts/archipelago/deploy.sh'
```

**Comment by DiegoPino** [comment]
@giancarlobi makes sense. I will document that this script is run without -u option and will add, just as a security thing, a `chown -R www-data` at the end of the update.sh file. Won't hurt to have it like that. Give me 30 minutes to update the script to have the that in place at the end, will let you know and then you can merge. Thanks!!

**Comment by giancarlobi** [comment]
Great, it could be tomorrow as here we are near supper time ;)

Il Lun 19 Ago 2019, 18:07 Diego Pino Navarro <notifications@github.com> ha
scritto:

**Comment by DiegoPino** [comment]
Perfect. Lets deal with this tomorrow, i have other pressing code to pull too.
See you tomorrow!

Cheers

**Comment by giancarlobi** [comment]
@DiegoPino now is perfect!
```
~/archipelago-deployment$ docker exec -ti esmero-php bash -c 'scripts/archipelago/update.sh'

Updating Archipelago Packages to whatever is latest in this release!
Running as root
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information                                                          Updating dependencies (including require-dev)         Package operations: 0 installs, 1 update, 0 removals
  - Updating strawberryfield/webform_strawberryfield dev-8.x-1.0-beta1 (1fd7b50 => 5e20cc4):  Checking out 5e20cc41f7
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
 [success] Cache rebuild complete.
Taking ownership of drupal modules for the www-data user, this can take a little while!If you see no errors, you are up to date! Done.
```

**Review by giancarlobi — APPROVED** [review]
Great!

**Comment by DiegoPino** [comment]
@giancarlobi++ please merge =)

**Comment by giancarlobi** [comment]
Done!

**Pull request merged**
