### PR TITLE
ISSUE-193: PHP debug docker container needs update

### LINKED ISSUE #193: PHP debug docker container needs update
# What?

Part of #191 

Update docker-compose.dev.yml to use PHP 8 dev docker container.

### PR DESCRIPTION
**Pull request by aksm**
Resolves #193

### CODE REVIEW

**Comment by DiegoPino** [comment]
@aksm thanks. Yes! Also, did you ever finish testing your own PHP8 image? The ones referenced here are still the ones I built without intl. I'm ok for today with this but goal would be to be sure 100% those new images do all the rest. Thanks

**Comment by aksm** [comment]
> @aksm thanks. Yes! Also, did you ever finish testing your own PHP8 image? The ones referenced here are still the ones I built without intl. I'm ok for today with this but goal would be to be sure 100% those new images do all the rest. Thanks

@DiegoPino Last I checked it was working, but will test again with everything updated. Does the debug container need to have it as well?

**Comment by DiegoPino** [comment]
Yes the debug container too, once the other one is tested. Maybe to avoid overlapping/having a rollback you can tag the new ones as 1.1.0?

**Comment by DiegoPino** [comment]
The debug container builds in not time since it extends the base one with a few extras

**Pull request merged**
