### PR TITLE
Issue 20b: Combine Xdebug work of Marlo and Diego

### PR DESCRIPTION
**Pull request by DiegoPino**
See #21 

# What is new?

This is a continuation of @marlo-longley's works on setting, documenting and using Xdebug to aid in Archipelago development.

There is some ngnix mapping and a video coming from Marlo himself too!

@marlo-longley Marlo. Can you please add in the comments some explanations of your work on this branch. That would help. Also do we need to update Documentation for xdebug?

Thanks for your work here

### CODE REVIEW

**Comment by marlo-longley** [comment]
@DiegoPino thanks for making this PR. Easier to communicate here!
OK yes, let's leave /xdebug with the .txt file. But the yml file should replace the `docker-compose.dev.yml` in the root.

**Comment by marlo-longley** [comment]
@DiegoPino the only reason I thought to prefer the online cookie creation method, is that the file we have stored in `xdebug/jsbookmarks-for-xdebug.txt` seems like it has an expire date (July 2020) so this could become dated, and if you create via the Internet, the date will be valid.

**Comment by DiegoPino** [comment]
Which has a simple fix: change the date to 2022?

**Comment by marlo-longley** [comment]
@DiegoPino 
Please disregard my comments about the date above.
I misread the script. The date is fine as it is.

Re: documentation. I updated it in this pull https://github.com/esmero/archipelago-documentation/pull/32. It should be ready to go.

In light of that, I approve this work and think we are good. 

Any more thoughts?

**Review by marlo-longley — APPROVED** [review]

**Pull request merged**
