### PR TITLE
ISSUE-162: Update configs for Data CreativeWorks Series Drupal view

### PR DESCRIPTION
**Pull request by aksm**
Resolves addendum to #162 , i.e.

- for the Creative Work Series Children View Sort Criteria, adding the sequence_id and removing the Changed (Exposed)
- for the Digital Object and Digital Object Collection Display modes for "Digital Object with Thumbnail for Grid", disabling Last Modified

### CODE REVIEW

**Comment by alliomeria** [comment]
Thanks @aksm! Will take a look & share any feedback shortly.

**Review by DiegoPino — CHANGES_REQUESTED** [review]
@aksm I think for this we need to keep both, sort first by sequence_id and as secondary by changed. That way Objects that do not have a sequence_id still get sorted by something.  @alliomeria what do you think?

Sorry for the late response on this @aksm

**Comment by aksm** [comment]
> @aksm I think for this we need to keep both, sort first by sequence_id and as secondary by changed. That way Objects that do not have a sequence_id still get sorted by something. @alliomeria what do you think?
> 
> Sorry for the late response on this @aksm

Pushed the commit, but I can roll back if we decide otherwise.

**Comment by DiegoPino** [comment]
@aksm sorry here, let's check this again, I have some doubts now about the first 2 YML files (dependencies)

**Comment by DiegoPino** [comment]
@aksm will close this one, I think the latest configs brought it in. Will double check just in case.

**Pull request closed without merging**
