### PR TITLE
Update docker-compose files to work with the new MinIO console

### LINKED ISSUE #108: Move to minio/console before MINIO UI is deprecated
See https://github.com/minio/console#docker

Seems like MINIO UI will be deprecated. Has served us well but Console seems richer also and since it won't be running on the same Container may have more security and will have the benefit of allowing User Management and policies to be setup via UI too.

### LINKED ISSUE #118: MinIO web interface no longer accessible
Since [RELEASE.2021-07-08T01-15-01Z](https://github.com/minio/minio/releases/tag/RELEASE.2021-07-08T01-15-01Z), MinIO has removed the builtin MinIO browser in favour of integrating their MinIO Console product and providing an automatic redirect from the MinIO API.

Therefore deployments of Archipelago built after this version was released will pull a `minio/minio:latest` image that contains this breaking change, and the esmero-minio container will not be accessible via the web browser interface.

This is because the service will attempt to issue a redirect to the new Console port, which is obviously unavailable outside the container (although API requests on port 9000 will still work, as these don't get redirected, meaning this problem will be "invisible" to existing deployments that just update the image).

As far as I can see, there are two options for fixing:
1) Pin the `docker-compose.yml` files to a version of MinIO from before this breaking change, rather than `latest`
2) Update the MinIO configuration to work with the new Console access

Happily the second of these is very simple, so I'll send a PR shortly in case that's the route you wish to go down.

Thanks for all the great work on Archipelago so far - really excited to be trying out RC2 and hoping we will make a magical set of islands a permanent part of our DL setup :)

### PR DESCRIPTION
**Pull request by mbennett-uoe**
Open/bind port 9001 in Docker, and update the MinIO start command to use this port for the console interface.

Resolves https://github.com/esmero/archipelago-deployment/issues/118

The `minio/minio:latest` docker image includes the console inside the same container as the server, so this PR will also resolve https://github.com/esmero/archipelago-deployment/issues/108 unless it is desired to run a standalone instance of the MinIO Console in a separate container.

### CODE REVIEW

**Comment by DiegoPino** [comment]
@mbennett-uoe great! Thanks so much 👍  Just tested and all works. Also the New console is quite nice!

image

Any chance you know which Docker Container tag was the last one that used still the old console?

I want to make a tiny change here. Make this pull against RC3 (upcoming very soon no change on your side I think I can just change here the Branch target) and then fix RC2 to not use "latest" so current RC2 documentation still applies to the active release.

What do you think? Does that sound like a good idea?

I also see that for "latest" we should update our MINIO ENV Credentials

WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated. Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
API: http://192.168.96.7:9000 http://192.168.80.5:9000 http://127.0.0.1:9000
Console: http://192.168.96.7:9001 http://192.168.80.5:9001 http://127.0.0.1:9001
Documentation: https://docs.min.io

Not sure if that applies to archipelago-deployment-live where we are using minio as AWS S3 router or not

**Comment by mbennett-uoe** [comment]
> Any chance you know which Docker Container tag was the last one that used still the old console?

I'm afraid not, I discovered the issue only yesterday when building a new deployment of RC2. I'll have a look through the container registry and see if I can determine it, though.

> I want to make a tiny change here. Make this pull against RC3 (upcoming very soon no change on your side I think I can just change here the Branch target) and then fix RC2 to not use "latest" so current RC2 documentation still applies to the active release.
>
>What do you think? Does that sound like a good idea?

I think this sounds like a good approach - I had also noticed the new method of adding a bucket (i.e the coral + sign no longer exists), but I wasn't sure if to include an update for the documentation alongside the technical change, or whether to do it separately.

> I also see that for "latest" we should update our MINIO ENV Credentials
>
> WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated. Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD

I saw this in the docker logs for the container when I was debugging the issue with accessing the web interface, but since it is a warning, and the current credential approach is still working, I didn't consider it critical (yet!). I will investigate the change to the environment variables (maybe it's just a naming change and therefore a very simple "fix", but maybe there is also more than that) and append it to this PR or open a new one as appropriate.

> Not sure if that applies to archipelago-deployment-live where we are using minio as AWS S3 router or not

I'm afraid I'm just using the local deployment (although on a VM rather than _actually_ locally), so I haven't investigated if the same issue applies to the live deployment repository.

**Comment by DiegoPino** [comment]
@mbennett-uoe ok, the last release that had MINIO Browser was 
RELEASE.2021-06-07T21-40-51Z, so if you are OK I will update RC2 branches for that and change the base Branch for this Pull to RC3.

**Review by DiegoPino — APPROVED** [review]
Great. New Console works perfectly.

**Pull request merged**
