### PR TITLE
ISSUE-19c:New 8.8.1 Validated Sync Configs

### PR DESCRIPTION
**Pull request by DiegoPino**
See #19 

# What is new?

This is our set of new (or better said updated) configurations for 8.x-1.0-beta2 deployment. These have been tested during a, from scratch deployment and the "augmente" with a full dump on a clean machine.

We can of course still make them better! And we should, there is just so much in these configs, lots-a-lots-of-a-yamls.

#  What is pending?

- How these ones react when applied over a running Beta1?
- New Config Inspector is way more thorough and has exposed a few invalid/missing/schema declarations. Some of them on our side (will be fixed in each module during branch creation, i promise!) but also some outside of our scope, and there is little we can do really?
Status report | { Archipelago Commons 8 x-1 0-beta2 }

As requested in https://github.com/esmero/format_strawberryfield/issues/30 I also tried to "update the labels" for our Field Descriptive Metadata `DS Copy fields` from `raw`, `static media`, etc but now that i look at them (Virtual Copy 1 of ...) the new names are just really silly and i would love to have some suggestions (HELP folks), somtehing as simple  (SBF-1) or something, or like some fun names, but easy to remember, because they are multi purpose but also, we provide by default a certain use, so labels kinda speak to that? Anyway @giancarlobi @marlo-longley @mitchellkeaney i kept the machine names the same (a need to allow beta1 users to have an easy update path), just changed the labels. Please, give me advice. Also, please advice on  funny and relaxed labels if possible =)

Moving Forward!
More to come.
Chao

### CODE REVIEW

**Comment by mitchellkeaney** [comment]
Mostly for myself to externally synthesize a conversation I just had with Diego IRL, I write the following:

The field names we give as default with a fresh deployment of Archipelago are "Media", "Formatted Object Metadata", "Descriptive Metadata" and "Static Media". The hidden (or not so explicit) things here are 1) these fields are all copies of the same Strawberry Field module, 2) it's virtually unknown which one is the master module all the copies stem from and mostly 3) what the heck do those names even mean?

They don't mean anything! Well, not necessarily. And the reason is because you can assign any formatter to any of those fields. So, for fun and the sake of making our users happy: we should rename these default fields so they don't stick and end up looking like sticks in the mud (on the shore of a beautiful chain of islands somewhere in the middle of the Mediterranean sea).

My (fun) suggestion:
Strawberry Sun
Strawberry Sky
Strawberry Moon
Strawberry Dream

My (not-so-fun-but-maybe-more-universally-understood-and-practical) suggestion:
SBF-1
SBF-2
SBF-3
SBF-4

**Comment by DiegoPino** [comment]
@mitchellkeaney thanks for bringing my explanation to clear terms! This is great. I guess this should find its space in the docs too 👀 
About the names, i like the idea of Sun, Moon, etc. Have to think about how much coherence we maintain with the rest of the concepts we have been pushing. The SBF-1 to 4 now make less sense to me (after sleeping) because they kinda suggest an order. And none of them have an order other than the one Power users provide when dragging the fields in each display. So SBF-1 could end being put out in position 4! Keep the ideas flowing. It could be also cool to denote that in that set, there is actually one that is real, the real, concrete source for your metadata.

**Comment by marlo-longley** [comment]
@DiegoPino @mitchellkeaney I think SBF1-4 is a great solution. Hopefully will clarify to people some inner workings of Archipelago. Thanks!

**Comment by mitchellkeaney** [comment]
@marlo-longley @DiegoPino - per conversations offline and inside my own head, I actually think having SBF 1 - 4 may not be the best idea because, in a way, it implies that there is a hierarchy or an order to which formatter is first, second, third, etc. when this simply isn't the case.

One thing we should for sure do is make the master module clearly defined as the master. The fact that the rest are copies doesn't need to be exposed to the user except through documentation, if at all.

I like the idea of each field being named "Strawberry" but each one a different language: la fresa, die Erdbeere, etc.

**Comment by marlo-longley** [comment]
@mitchellkeaney @DiegoPino I agree that the fact these are copy fields is not relevant, and in fact confusing, for the users. Only someone who understands Display Suite in Drupal will get it really. The data is the same.

I like your approach Mitchell of trying thematic naming schemes like languages, astronomy. If naming them 1-4 won't work, I  think now we are encountering the problem of differentiating them at all (though I understand the specific objection about 1-4 was regarding hierarchy). I  If this is the case, is there a problem simply naming them all "Strawberryfield" ?

For me the least confusing thing is to give them all the same name, since they are the same, "Strawberryfield Data" -- actually, when I looked at my local Archipelago, that is what I labeled them myself to keep from getting confused last year. Maybe not fun and relaxed naming however?

**Comment by DiegoPino** [comment]
@marlo-longley @mitchellkeaney @giancarlobi settings are looking better now, i will give these ones a try and will then move into improving and testing. I need to update more in this branch to make beta2 deployment possible, but moving forward. Will all let you know when we are ready.

**Pull request merged**
