### PR TITLE
ISSUE-164: Update Drupal facets module so range slider functions

### LINKED ISSUE #164: Update Drupal facets module so range slider functions
# What?
[A recent release (16a4e249)](https://git.drupalcode.org/project/facets/-/commit/16a4e249920165858e6fb70804a547532ad4d765) of the Drupal facets module doesn't work with [the patch](https://www.drupal.org/files/issues/2021-11-12/issue-3153622-nouislider_25.patch) we've been using for the range slider UI. [The newest release (8a9574df)](https://git.drupalcode.org/project/facets/-/commit/8a9574df5bfd4b4a528a3354ecb3ed77740abf43), however, accepts the patch, and the slider functions as tested.

### PR DESCRIPTION
**Pull request by aksm**
Resolves #164

### CODE REVIEW

**Comment by DiegoPino** [comment]
@aksm this is great but won't work if "lates" facet module hash (EDITED) and the extra fetch time/source/etc is not part of the deployment composer.lock
You need to add an updated composer.lock or this won't apply clean

**Comment by aksm** [comment]
@DiegoPino Hmm, the hash is updated in the lock file. Did I miss something else?

**Comment by DiegoPino** [comment]
Hi, sorry for being so picky. Normally the hash is enough but you will notice (if you do a diff on your lock with the default one) that also the fetch time will change and maybe even the pointer to the source.

**Comment by aksm** [comment]
@DiegoPino Not picky. My mistake. Fixed!

**Comment by DiegoPino** [comment]
@patdunlavey @aksm if you are OK I will merge what is open into RC3 and then freeze the branch.. you OK? Also I need the same pull(s) for archipelago-deployment-live...

**Review by DiegoPino — APPROVED** [review]

**Comment by DiegoPino** [comment]
@aksm still waiting for the archipelago-deployment-live version of this one. Could you roll that one too? Merged here in the meantime

**Pull request merged**
